FutureFarm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('production_cycle.urls')),
    path('account/', include('account.urls'))
]

account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(redirect_field_name='/cycles/'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register_user, name='register')
]

production_cycle/urls.py
from django.urls import path
from production_cycle import views

urlpatterns = [
    path('cycles/', views.CycleListView.as_view(), name='cycles'),
    path('create-cycle/', views.CycleCreateView.as_view(), name='createCycle'),
    path('cycle-detail/<str:pk>/',
         views.CycleDetailView.as_view(), name='cycleDetail'),
    path('delete-cycle/<str:pk>/',
         views.CycleDeleteView.as_view(), name='deleteCycle'),
    path('update-cycle/<str:pk>/',
         views.CycleUpdateView.as_view(), name='updateCycle'),
    path('create-slaugter/', views.SlaughterCreateView.as_view(),
         name='createSlaughter'),
    path('update-slaugter/<str:pk>',
         views.SlautherUpdateView.as_view(), name='updateSlaughter'),
    path('delete-slaugter/<str:pk>',
         views.SlaugterDeleteView.as_view(), name='deleteSlaughter'),
    path('create-day/', views.DayCreateView.as_view(), name='createDay'),
    path('update-day/<str:pk>', views.DayUpdateView.as_view(), name='updateDay'),
    path('day/<str:pk>', views.day, name='day'),
    path('delete-day/<str:pk>', views.DayDeleteView.as_view(), name='deleteDay')
]

production_cycle/models.py
from django.db import models


class Day(models.Model):
    date = models.DateTimeField(auto_now=True)
    cycle_day = models.IntegerField(default=0)
    deads = models.IntegerField(default=0)
    selection = models.IntegerField(default=0)
    daily_mortality_rate = models.FloatField(default=0)
    feed_consumption = models.FloatField(default=0)
    wather_consumption = models.FloatField(default=0)
    average_body_weight = models.FloatField(default=0)
    temperature = models.FloatField(default=0)
    humidity = models.FloatField(default=0)
    medications = models.CharField(max_length=100, default="brak")
    cycle = models.ForeignKey("Cycle", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date)


class Cycle(models.Model):
    date_of_insertion = models.DateTimeField(auto_now=True)
    hybryd = models.CharField(max_length=30, default="hybryd")
    herd_size = models.IntegerField(default=0)
    chick_avarage_weight = models.FloatField(default=0)
    age_of_the_reproductive_stock = models.CharField(
        max_length=30, default="age")
    hatchery = models.CharField(max_length=30, default="hatchery")
    current_herd_size = models.IntegerField(default=herd_size)

    def __str__(self):
        return str(self.id)


class Slaughter(models.Model):
    date = models.DateTimeField(auto_now=True)
    cycle = models.ForeignKey("Cycle", on_delete=models.CASCADE)
    day_id = models.CharField(max_length=50)
    quantity = models.IntegerField(default=0)
    weight = models.FloatField(default=0)
    average_weight = models.FloatField(default=0)
    slaughterhouse = models.CharField(max_length=50)


class FeedDelivery(models.Model):
    STARTER = 'ST'
    GROWER = 'GR'
    FINISHER = 'FR'
    FEED_CHOICES = [
        (STARTER, 'Starter'),
        (GROWER, 'Grower'),
        (FINISHER, 'Finisher')
    ]
    date = models.DateTimeField(auto_now=True)
    choices = models.CharField(
        max_length=2, choices=FEED_CHOICES, default=STARTER)
    quantity = models.FloatField(default=0)
    price = models.FloatField(default=1)
    cycle = models.ForeignKey("Cycle", on_delete=models.CASCADE)


class Standards(models.Model):
    cycle_day = models.IntegerField(default=0)
    average_body_weight = models.FloatField(default=0)
    daily_weight_gain = models.FloatField(default=0)
    average_daily_weight_gain = models.FloatField(default=0)
    feed_consumption = models.FloatField(default=0)
    cumulative_feed_consumption = models.FloatField(default=0)
    wather_consumption = models.FloatField(default=0)
    cumulative_wather_consumption = models.FloatField(default=0)
    feed_conversion = models.FloatField(default=0)

    def __str__(self):
        return str(self.cycle_day)

production_cycle/forms.py
from django.db.models import fields
from django.forms import ModelForm
from .models import Day, Cycle, FeedDelivery, Slaughter


class DayForm(ModelForm):
    class Meta:
        model = Day
        fields = ['cycle_day', 'deads', 'selection', 'feed_consumption', 'wather_consumption',
                  'average_body_weight', 'temperature', 'humidity', 'medications', 'cycle']

        def __init__(self, fields, cycle):
            self.fields = fields
            self.model.cycle = cycle


class CycleForm(ModelForm):
    class Meta:
        model = Cycle
        fields = ['hybryd', 'herd_size', 'chick_avarage_weight',
                  'age_of_the_reproductive_stock', 'hatchery']


class SlaughterForm(ModelForm):
    class Meta:
        model = Slaughter
        fields = ['cycle', 'day_id', 'quantity', 'weight',
                  'average_weight', 'slaughterhouse']


class FeedDeliveryForm(ModelForm):
    class Meta:
        model = FeedDelivery
        fields = ['choices', 'quantity', 'price', 'cycle']

production_cycle/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.db.models.signals import post_delete, post_save
from django.core.signals import request_started
from django.dispatch import receiver
from .models import *
from .forms import *


class CycleListView(ListView):
    model = Cycle
    template_name = 'production_cycle/cycle/cycles.html'
    context_object_name = 'cycles'


class CycleCreateView(CreateView):
    model = Cycle
    form_class = CycleForm
    template_name = 'production_cycle/cycle/create.html'
    success_url = '/cycles/'


class CycleDetailView(DetailView):
    model = Cycle
    context_object_name = 'cycle'
    template_name = 'production_cycle/cycle/detail.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class CycleDeleteView(DeleteView):
    model = Cycle
    success_url = '/cycles/'
    template_name = 'production_cycle/cycle/delete.html'


class FeedDeliveryCreateView(CreateView):
    model = FeedDelivery
    form_class = FeedDeliveryForm
    template_name = 'production_cycle/create_feed_delivery.html'


class CycleUpdateView(UpdateView):
    model = Cycle
    fields = ['hybryd', 'herd_size', 'chick_avarage_weight',
              'age_of_the_reproductive_stock', 'hatchery', 'current_herd_size']
    template_name_suffix = '_update_form'


class SlaughterCreateView(CreateView):
    model = Slaughter
    form_class = SlaughterForm
    template_name = 'production_cycle/create_slaughter.html'
    success_url = '/cycles/'


@receiver(post_save, sender=Slaughter)
def update_by_creating_slaughter(sender, **kwargs):
    instance = kwargs['instance']
    cycle = Cycle.objects.get(id=instance.cycle.id)
    cycle.current_herd_size -= instance.quantity
    cycle.save()


class SlautherUpdateView(UpdateView):
    model = Slaughter
    form_class = SlaughterForm
    template_name = 'production_cycle/update_slaughter.html'
    success_url = '/cycles/'

    def get(self, request, *args, **kwargs):
        slaughter = self.get_object()
        cycle = Cycle.objects.get(id=slaughter.cycle.id)
        cycle.current_herd_size += slaughter.quantity
        cycle.save()
        return super().get(request, *args, **kwargs)


class SlaughterListView(ListView):
    model = Slaughter
    template_name = ''
    context_object_name = 'slaughters'


class SlaugterDeleteView(DeleteView):
    model = Slaughter
    template_name = 'production_cycle/delete_slaughter.html'
    context_object_name = 'slaughter'
    success_url = '/cycles/'


@receiver(post_delete, sender=Slaughter)
def update_by_deleting_slaughter(sender, **kwargs):
    instance = kwargs['instance']
    cycle = Cycle.objects.get(id=instance.cycle.id)
    cycle.current_herd_size += instance.quantity
    cycle.save()


def day(request, pk):
    day = Day.objects.get(id=pk)

    context = {
        'day': day
    }
    return render(request, 'production_cycle/day.html', context)


class DayCreateView(CreateView):
    model = Day
    form_class = DayForm
    template_name = 'production_cycle/create_day.html'
    success_url = '/cycles/'


@receiver(post_save, sender=Day)
def update_by_creating_day(sender, **kwargs):
    instance = kwargs['instance']
    cycle = Cycle.objects.get(id=instance.cycle.id)
    cycle.current_herd_size -= instance.deads
    cycle.save()


class DayUpdateView(UpdateView):
    model = Day
    form_class = DayForm
    template_name = 'production_cycle/update_day.html'
    success_url = '/cycles/'

    def get(self, request, *args, **kwargs):
        day = self.get_object()
        cycle = Cycle.objects.get(id=day.cycle.id)
        cycle.current_herd_size += day.deads
        cycle.save()
        return super().get(request, *args, **kwargs)


class DayDeleteView(DeleteView):
    model = Day
    template_name = 'production_cycle/delete_day.html'
    success_url = '/cycles/'


@receiver(post_delete, sender=Day)
def update_by_deleting_day(sender, **kwargs):
    instance = kwargs['instance']
    cycle = Cycle.objects.get(id=instance.cycle.id)
    cycle.current_herd_size += instance.deads
    cycle.save()

production_cycle/templates/production_cycle/cycle/create.html
{% extends 'production_cycle/base.html' %}
{% load static %}
{% block content %}

<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}

    <input class="btn btn-info" type="submit" value="Dodaj"</input>

</form>

{% endblock %}

production_cycle/templates/production_cycle/cycle/cycles.html
{% extends 'production_cycle/base.html' %} 
{% load static %} 
{% block content %}

{% for cycle in cycles reversed %}

<div class="grid-item">
  <h1 id="welcome-title">Uboje</h1>
  <table class="table table-borderless">
    <thead>
      <th>Data</th>
      <th>Cykl</th>
      <th>Ilość</th>
    </thead>
    <tbody>
      {% for slaughter in cycle.slaughter_set.all reversed %}
      <tr>
        <td>{{slaughter.date}}</td>
        <td>{{slaughter.cycle}}</td>
        <td>{{slaughter.quantity}}</td>
        <td>
          <a class="btn btn-sm btn-warning" href="{% url 'updateSlaughter' slaughter.id%}">Edytuj</a>
          <a class="btn btn-sm btn-danger" href="{% url 'deleteSlaughter' slaughter.id%}">Usuń</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="grid-item">
  <h1 id="welcome-title">Aktualny rozmiar stada:</h1>
  <br>
  <h3>{{cycle.current_herd_size}}</h3>
  <div class="border-top border-bottom p-3 transaction">
    <a href="{% url 'createCycle' %}" class="btn btn-info">Dodaj</a>
    <a href="{% url 'cycleDetail' cycle.id %}" class="btn btn-info">info</a>
    <br />
  </div>
  <br>
  <h1 id="welcome-title">Raporty dzienne</h1>
  <table class="table table-borderless">
    <thead>
      <th>Data</th>
      <th>Dzień cyklu</th>
      <th>Upadki</th>
      <th>Cykl</th>
    </thead>
    <tbody>
      {% for day in cycle.day_set.all reversed %}
      <tr>
        <td>{{day.date}}</td>
        <td>{{day.cycle_day}}</td>
        <td>{{day.deads}}</td>
        <td>{{day.cycle}}</td>
        <td>
          <a class="btn btn-sm btn-info" href="{% url 'day' day.id%}">Info</a>
          <a class="btn btn-sm btn-warning" href="{% url 'updateDay' day.id%}">Edytuj</a>
          <a class="btn btn-sm btn-info" href="{% url 'createDay' %}">Dodaj</a>
          <a class="btn btn-sm btn-danger" href="{% url 'deleteDay' day.id%}">Usuń</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endfor %} {% endblock %}

production_cycle/templates/production_cycle/cycle/delete.html
{% extends 'production_cycle/base.html' %}
{% load static %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Usunąć cykl "{{ object.id }}"?</p>
    <input type="submit" value="potwierdz">
</form>

{% endblock %}

production_cycle/templates/production_cycle/cycle/detail.html
{% extends 'production_cycle/base.html' %} {% load static %} {% block content %}

<table class="table table-borderless">
  <p>Nr cyklu: {{object.id}}</p>
  <p>Data wstawienia: {{object.date_of_insertion}}</p>
  <p>Hybryd: {{object.hybryd}}</p>
  <p>Rozmiar stada: {{object.herd_size}}</p>
  <p>Średnia waga pisklęcia: {{object.chick_avarage_weight}}</p>
  <p>Wiek stada reprodukcyjnego:{{object.age_of_the_reproductive_stock}}</p>
  <p>Wylegarnia: {{object.hatchery}}</p>
  <p>Aktualny rozmiar stada: {{object.current_herd_size}}</p>
  <div>
    <a class="btn btn-sm btn-info" href="{% url 'cycles'%}">Wróć</a>
    <a class="btn btn-sm btn-warning" href="{% url 'updateCycle' object.id %}">Edytuj</a>
    <a class="btn btn-sm btn-danger" href="{% url 'deleteCycle' object.id %}">Usuń</a>
    <a class="btn btn-sm btn-info" href="{% url 'createSlaughter' %}">Dodaj ubój</a>
  </div>
</table>
<div class="grid-item">
  <h1 id="welcome-title">Uboje</h1>
  <table class="table table-borderless">
    <thead>
      <th>Data</th>
      <th>Cykl</th>
      <th>Ilość</th>
    </thead>
    <tbody>
      {% for slaughter in cycle.slaughter_set.all reversed %}
      <tr>
        <td>{{slaughter.date}}</td>
        <td>{{slaughter.cycle}}</td>
        <td>{{slaughter.quantity}}</td>
        <td>
          <a class="btn btn-sm btn-warning" href="{% url 'updateSlaughter' slaughter.id%}">Edytuj</a>
          <a class="btn btn-sm btn-danger" href="{% url 'deleteSlaughter' slaughter.id%}">Usuń</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

production_cycle/templates/production_cycle/cycle/update.html
{% extends 'production_cycle/base.html' %}
{% load static %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edytuj">
</form>

{% endblock %}